apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    editable: true
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: "GET"
      keepCookies: []
